# Add 'Documentation' label to any file changes within 'docs' or 'guides' folders
documentation:
- changed-files:
  - any-glob-to-any-file:
    - docs/*
    - guides/*
    - '**/*.md'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature']

# Add 'bug' label to any PR where the head branch name starts with `bug` or has a `bug` section in the name
bug:
  - head-branch: ['^bug', 'bug']

# Add 'fix' label to any PR where the head branch name starts with `fix` or has a `fix` section in the name
fix:
  - head-branch: ['^fix', 'fix']

# Add 'enhancement' label to any PR where the head branch name starts with `enhancement` or has a `enhancement` section in the name
enhancement:
  - head-branch: ['^enhancement', 'enhancement']

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'PRODUCCION'